
###
POST http://localhost:8080/admin/reset

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul1@bettercall.com"
}

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "${userID1}"
}
